### ISSUE TITLE
ASK ??

### ISSUE THREAD

**Issue by GMCadiom** [xdevs23/android_device_avus_a84#1]
Is That Tree Work On Stock mt6592 v3.4.67 Kernel ??

**Comment by xdevs23** [comment]
It's for a mt6592 device

**Comment by GMCadiom** [comment]
i mean is i can use brebuild stock kernel or i need a custom one ??

**Comment by xdevs23** [comment]
Prebuilt

**Comment by GMCadiom** [comment]
so last Q
what that Prebuilt kernel version ??
